### PR TITLE
repository setup for first release

### PR DESCRIPTION
**Pull request by moedn**
from my perspective we're good to go once this is merged :tada: 

The v1.0.0 release should have the following ZIP attached in the release notes:

[frame+spacer-STLs.zip](https://github.com/umbertozanovello/MagnetTestStation/files/13705566/spacer-STLs.zip)

other than that the only thing left to decide is _where_ the main repo should be → should it stay under the namespace https://github.com/umbertozanovello/ or would you prefer to see it somewhere under https://gitlab.com/osii ?

### CODE REVIEW

**Comment by umbertozanovello** [comment]
Hi! Thank you.
I would move it under  https://gitlab.com/osii but for now I'd like to leave also the github version since this is the object of an ISMRM abstract and the abstract points here. I can add a note into the readme saying that the project has been moved to gitlab osii and it's no more maintened here. What do you think?

**Comment by moedn** [comment]
sounds reasonable :ok: 

I imported the project into the `tools` group: https://gitlab.com/osii/tools/MagnetTestStation , will do some last tweaks and then announce it on Matrix :heart: 

I'd like to grant you owner rights for this repo (since you're the maintainer of it) → could you please tell me your gitlab handle? (couldn't find `umbertozanovello`)

**Comment by umbertozanovello** [comment]
I access gitlab through my institution google account. Try with u.zanovello
Thanks a lot!!

**Comment by moedn** [comment]
:heavy_check_mark: done, thanks!

**Pull request merged**
